# Generated by Django 5.0.1 on 2024-11-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_present',
            new_name='is_early_leave',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
